require "test_helper"

class AuthControllerTest < ActionDispatch::IntegrationTest
  context 'unauthenticated' do
    should 'not login with wrong credentials' do
      post api_v1_auth_login_path, params: { email:'user@example.com', password:'fail' }
      assert_response :unauthorized
    end
  end

  context 'authenticated' do
    setup do
      # using setup here for learning puporses only.
      @user = users(:user1)
      @password = '123456'
      # @user.password_digest is generated by BCrypt in user fixture
    end

    should 'login with correct credentials' do
      post api_v1_auth_login_path, params: {email: @user.email, password: @password }

      # 200 is enough..
      assert_response :success

      # ...but I'll test token presence also (learning purposes)
      json = JSON.parse(response.body)
      assert_not_empty json["token"]
    end
  end
end
